type ExampleScreen =
  | "light button states"
  | "dark button states"
  | "light buttons"
  | "dark buttons"
  | "light cards"
  | "dark cards"
  | "light chips states"
  | "dark chips states"
  | "light chips"
  | "dark chips"
  | "light dialogs"
  | "dark dialogs"
  | "light fabs"
  | "dark fabs"
  | "light select"
  | "dark select"
  | "light nav bar"
  | "dark nav bar"
  | "light app bar"
  | "dark app bar";
