type ExampleScreen =
  | "light button states"
  | "dark button states"
  | "light buttons"
  | "dark buttons"
  | "light cards"
  | "dark cards"
  | "light chips"
  | "dark chips"
  | "light dialogs"
  | "dark dialogs"
  | "light fabs"
  | "dark fabs"
  | "light select"
  | "dark select";
